src/Entity/EventTime.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventTimeRepository")
 */
class EventTime
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="guid")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @Assert\DateTime()
     */
    private $startTime;

    /**
     * @ORM\Column(type="integer")
     */
    private $entries = 0;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Registration", mappedBy="eventTime", orphanRemoval=true)
     */
    private $registrations;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Event", inversedBy="times")
     * @ORM\JoinColumn(nullable=false)
     * @var Event
     */
    private $event;

    /**
     * EventTime constructor.
     */
    public function __construct()
    {
        $this->registrations = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    /**
     * @param \DateTimeInterface $startTime
     * @return EventTime
     */
    public function setStartTime(\DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getEntries(): ?int
    {
        return $this->entries;
    }

    /**
     * @param int $entries
     * @return EventTime
     */
    public function setEntries(int $entries): self
    {
        $this->entries = $entries;

        return $this;
    }

    /**
     * @return Collection|Registration[]
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    /**
     * @param Registration $registration
     * @return EventTime
     */
    public function addRegistration(Registration $registration): self
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations[] = $registration;
            $registration->setEventTime($this);
        }

        return $this;
    }

    /**
     * @param Registration $registration
     * @return EventTime
     */
    public function removeRegistration(Registration $registration): self
    {
        if ($this->registrations->contains($registration)) {
            $this->registrations->removeElement($registration);
            // set the owning side to null (unless already changed)
            if ($registration->getEventTime() === $this) {
                $registration->setEventTime(null);
            }
        }

        return $this;
    }

    /**
     * @return Event|null
     */
    public function getEvent(): ?Event
    {
        return $this->event;
    }

    /**
     * @param Event|null $event
     * @return EventTime
     */
    public function setEvent(?Event $event): self
    {
        $this->event = $event;

        return $this;
    }

    /**
     * @return int
     */
    public function getEntriesLeft()
    {
        return $this->event->getCapacity() - $this->entries;
    }

    /**
     * @param bool $isAdmin
     * @return bool
     */
    public function isAvailable(bool $isAdmin = false)
    {
        $haveOpenSlots = $this->getEvent()->getCapacity() === null || $this->getEvent()->getCapacity() > $this->entries;
        return $haveOpenSlots && (!$this->getEvent()->getIsOpen() || $isAdmin);
    }

    /**
     * @param bool $isAdmin
     * @return bool
     */
    public function getIsAvailable(bool $isAdmin = false)
    {
        return $this->isAvailable($isAdmin);
    }

    /**
     * @param int $count
     */
    public function increaseEntries(int $count = 1)
    {
        $this->entries += $count;
    }
}

src/Entity/FormConfig.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FormConfigRepository")
 */
class FormConfig
{
    const SIMPLE = 'simple';
    const GROUP = 'group';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="guid")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description = '';

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Form is empty")
     * @Assert\NotEqualTo(value="[]", message="Form is empty")
     */
    private $config = '';

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="formConfigs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type = self::SIMPLE;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\RegistrationEmailTemplate", mappedBy="formConfig", cascade={"persist", "remove"})
     */
    private $emailTemplate;

    /**
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return null|string
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return FormConfig
     */
    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param null|string $description
     * @return FormConfig
     */
    public function setDescription(?string $description): self
    {
        $this->description = '';
        if ($description !== null) {
            $this->description = $description;
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * @return array
     */
    public function getConfigParsed()
    {
        $parsed = json_decode($this->config, true);
        if ($parsed === null) {
            $parsed = [];
        }

        return $parsed;
    }

    /**
     * @param null|string $config
     * @return FormConfig
     */
    public function setConfig(?string $config): self
    {
        $this->config = '';
        if ($config !== null) {
            $this->config = $config;
        }

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    /**
     * @param \DateTimeInterface $created
     * @return FormConfig
     */
    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    /**
     * @return User|null
     */
    public function getOwner(): ?User
    {
        return $this->owner;
    }

    /**
     * @param User|null $owner
     * @return FormConfig
     */
    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * @return string
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param string $type
     */
    public function setType($type): void
    {
        $this->type = $type;
    }

    /**
     * @return RegistrationEmailTemplate|null
     */
    public function getRegistrationEmailTemplate(): ?RegistrationEmailTemplate
    {
        return $this->emailTemplate;
    }

    /**
     * @param RegistrationEmailTemplate|null $emailTemplate
     * @return FormConfig
     */
    public function setRegistrationEmailTemplate(?RegistrationEmailTemplate $emailTemplate): self
    {
        $this->emailTemplate = $emailTemplate;

        // set the owning side of the relation if necessary
        if ($emailTemplate !== null && $this !== $emailTemplate->getFormConfig()) {
            $emailTemplate->setFormConfig($this);
        }

        return $this;
    }

    /**
     * @return array
     */
    public function getFieldNames(): array
    {
        $names = [];

        foreach ($this->getConfigParsed() as $field) {
            $names[$field['label']] = $field['name'];
        }

        return $names;
    }
}

src/Entity/WorkshopTime.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WorkshopTimeRepository")
 */
class WorkshopTime
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="guid")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @Assert\DateTime()
     */
    private $startTime;

    /**
     * @ORM\Column(type="integer")
     */
    private $entries = 0;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Registration", mappedBy="workshopTime", orphanRemoval=true)
     */
    private $registrations;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Workshop", inversedBy="times")
     * @ORM\JoinColumn(nullable=false)
     * @var Workshop
     */
    private $workshop;

    /**
     * WorkshopTime constructor.
     */
    public function __construct()
    {
        $this->registrations = new ArrayCollection();
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    /**
     * @param \DateTimeInterface $startTime
     * @return WorkshopTime
     */
    public function setStartTime(\DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->startTime->add((new \DateTime('00:00'))->diff($this->getWorkshop()->getDuration()));
    }

    /**
     * @return int|null
     */
    public function getEntries(): ?int
    {
        return $this->entries;
    }

    /**
     * @param int $entries
     * @return WorkshopTime
     */
    public function setEntries(int $entries): self
    {
        $this->entries = $entries;

        return $this;
    }

    /**
     * @return Collection|Registration[]
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    /**
     * @return Workshop|null
     */
    public function getWorkshop(): ?Workshop
    {
        return $this->workshop;
    }

    /**
     * @param Workshop|null $workshop
     * @return WorkshopTime
     */
    public function setWorkshop(?Workshop $workshop): self
    {
        $this->workshop = $workshop;

        return $this;
    }

    /**
     * @return int
     */
    public function getEntriesLeft()
    {
        if($this->workshop->getCapacity() === null) {
            return 1000000;
        }
        return $this->workshop->getCapacity() - $this->entries;
    }

    /**
     * @param bool $isAdmin
     * @return bool
     */
    public function isAvailable(bool $isAdmin = false)
    {
        $haveOpenSlots = $this->getWorkshop()->getCapacity() === null || $this->getWorkshop()->getCapacity() > $this->entries;
        $isClosed = !$this->getWorkshop()->getIsOpen() || !$this->getWorkshop()->getCategory()->getEvent()->getIsOpen();
        return (!$isClosed || $isAdmin) && $haveOpenSlots;
    }

    /**
     * @param bool $isAdmin
     * @return bool
     */
    public function getIsAvailable(bool $isAdmin = false)
    {
        return $this->isAvailable($isAdmin);
    }

    /**
     * @param int $count
     */
    public function increaseEntries(int $count = 1)
    {
        $this->entries += $count;
    }
}

templates/Default/base.html.twig
{% extends 'base.html.twig' %}

{% block nav %}
    {% if is_granted('ROLE_USER') %}
        {{ parent() }}
    {% endif %}
{% endblock %}

{% block footer %}
<footer class="my-5 pt-5 text-muted text-center text-small">
    <ul class="list-inline">
        <li class="list-inline-item">
            <a href="{{ render(controller('App\\Controller\\LanguageController::changeLanguage', {'language': 'en'})) }}">
                <span class="flag-icon flag-icon-gb"></span>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="{{ render(controller('App\\Controller\\LanguageController::changeLanguage', {'language': 'lt'})) }}">
                <span class="flag-icon flag-icon-lt"></span>
            </a>
        </li>
    </ul>
</footer>
{% endblock %}

templates/Default/event.html.twig
{% extends 'Default/base.html.twig' %}

{% block title %}{{ eventTime.event.title }} | {{ eventTime.startTime|date('Y-m-d H:i') }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('style/css/datetimepicker/bootstrap-datetimepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('style/css/select2/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('style/css/select2/select2-bootstrap4.min.css') }}">
{% endblock %}

{% block body %}
    <div class="py-5 text-center">
        <h2>{{ eventTime.event.title }}</h2>
        <h6>{{ eventTime.startTime|date('Y-m-d H:i') }}</h6>
        <p class="lead">{{ eventTime.event.description|raw }}</p>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8">
            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ label }}" role="alert">
                        {{ message|trans }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% if workshopTime.isAvailable(is_granted('ROLE_USER')) %}
                <h4 class="mb-3">{% trans %}Registration{% endtrans %}</h4>
                <form name="registration" method="post">
                    {% if groupRegistration %}
                        {{ render(controller('App\\Controller\\Event\\FormController::renderForm', { 'config': eventTime.event.groupFormConfig.configParsed })) }}
                    {% else %}
                        {{ render(controller('App\\Controller\\Event\\FormController::renderForm', { 'config': eventTime.event.formConfig.configParsed })) }}
                    {% endif %}
                    <button class="btn btn-primary btn-lg btn-block" type="submit">{% trans %}Register{% endtrans %}</button>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/popper/popper.min.js') }}"></script>
    <script src="{{ asset('js/moment/moment.min.js') }}"></script>
    <script src="{{ asset('js/datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>
    <script src="{{ asset('js/select2/select2.full.min.js') }}"></script>
{% endblock %}

{% block javascript_inline %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();

            $(".datetimepicker").datetimepicker({
                'format': 'YYYY-MM-DD',
                'showClose': true
            });

            $(".formSelect").select2({
                theme: "bootstrap4"
            });
        });
    </script>
{% endblock %}

templates/Default/events.html.twig
{% extends 'Default/base.html.twig' %}

{% block title %}{{ event.title }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('style/css/custom/table.css') }}">
{% endblock %}

{% block body %}
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ event.title }}</h1>
        <p class="lead">{{ event.description }}</p>
    </div>

    <div>
        <iframe class="w-100" frameborder="0" style="border:0" allowfullscreen
                src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBipZdzMFb0iFrTE_5FEFwgmoEXd4--BoM&q={{ event.place|url_encode }}">
        </iframe>
    </div>

    {% if event.times is not empty %}
        <div class="card mt-2">
            <div class="card-body">
                <table class="table table-sm table-striped table-hover">
                    <thead>
                    <tr>
                        <th>{% trans %}Start Time{% endtrans %}</th>
                        <th>{% trans %}Duration{% endtrans %}</th>
                        <th>{% trans %}Places left{% endtrans %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for time in event.times %}
                        <tr class="clickable-row"
                            data-href="{{ path('registration', {'timeId': time.id}) }}">
                            <td>{{ time.startTime|date('Y-m-d H:i') }}</td>
                            <td>{{ event.duration|date('H:i') }}</td>
                            <td>
                                {% if event.capacity is not null %}
                                    <span class="badge badge-pill {% if time.available %}badge-primary{% else %}badge-secondary{% endif %}">{{ time.entriesLeft }}</span>
                                {% else %}
                                    {% trans %}Unlimited{% endtrans %}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block javascript_inline %}
    <script type="text/javascript">
        $(document).ready(function () {
            $(".clickable-row").click(function () {
                window.location = $(this).data("href");
            });
        });
    </script>
{% endblock %}

templates/Default/formChoice.html.twig
{% extends 'Default/base.html.twig' %}

{% block title %}{% trans %}Please choose registration type{% endtrans %}{% endblock %}

{% block body %}
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{% trans %}Please choose registration type{% endtrans %}</h1>
        <a class="btn btn-lg btn-primary"
           href="{{ path('registration_simple', {'timeId': timeId}) }}">{% trans %}Regular registration{% endtrans %}</a>
        <a class="btn btn-lg btn-primary"
           href="{{ path('registration_multi', {'timeId': timeId}) }}">{% trans %}Group registration{% endtrans %}</a>
    </div>
{% endblock %}

templates/Default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Index{% endtrans %}{% endblock %}

{% block body %}
<div class="container text-center">
    <h1 class="cover-heading mt-5">RengForm</h1>
    <h2 class="cover-heading">{% trans %}Registrations management system{% endtrans %}</h2>
    <p class="lead">RengForm is a registrations management system build specifically for events with multiple sub-events, lectures or workshops that all require separate registration. To cope with thet we build a system that allows you to build one or several registration forms and reuse them for all sub-events and even share them between events.</p>
</div>
{% endblock %}

templates/Default/multiEvent.html.twig
{% extends 'Default/base.html.twig' %}

{% block title %}{{ event.title }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('style/css/custom/table.css') }}">
    <style>
    .popup {
        font-size: 0.8em;
        position: absolute;
        z-index: 100;
    }
    </style>
{% endblock %}

{% block body %}
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{ event.title }}</h1>
        <h6>{{ event.date|date('Y-m-d H:i') }} - {{ event.endDate|date('Y-m-d H:i') }}</h6>
        <p class="lead">{{ event.description }}</p>
    </div>
    {% if not event.isOpen %}
        <div class="alert alert-danger" role="alert">
            {% trans %}Registration is closed.{% endtrans %}
        </div>
    {% endif %}
    

    {% for category in event.categories if not event.empty %}
        {% if category.workshops is not empty %}
            <div class="card mt-2">
                <div class="card-header">
                    <h5 class="card-title">{{ category.title }}</h5>
                </div>
                <div class="card-body">
                    <p>{{ category.description|raw }}</p>
                    <table class="table table-sm table-striped table-hover">
                        <thead>
                        <tr>
                            <th>{% trans %}Workshop name{% endtrans %}</th>
                            <th>{% trans %}Start Time{% endtrans %}</th>
                            <th>{% trans %}End Time{% endtrans %}</th>
                            <th>{% trans %}Places left{% endtrans %}{% if is_granted('ROLE_USER') %} ({% trans %}Registrations{% endtrans %}){% endif %}</th>
                            {% if is_granted('ROLE_USER') %}
                                <th>*</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for workshop in category.workshops %}
                            {% for time in workshop.times %}
                                <tr class="clickable-row">
                                    <td>
                                        <a class="link" href="{{ path('registration', {'timeId': time.id}) }}">{{ workshop.title }}</a>
                                        <div class="popup card" style="display: none;">
                                            <div class="card-body">
                                                {{ workshop.description|raw }}
                                            </div>
                                        </div>
                                    </td>
                                    <td>{{ time.startTime|date('H:i') }}</td>
                                    <td>{{ time.endTime|date('H:i') }}</td>
                                    <td>
                                        {% if workshop.capacity is not null %}
                                            <span class="badge badge-pill {% if time.available %}badge-primary{% else %}badge-secondary{% endif %}">{{ time.entriesLeft }}</span>
                                            {% if is_granted('ROLE_USER') %}<span class="badge badge-pill badge-success">{{ time.entries }}</span>{% endif %}
                                        {% else %}
                                            {% trans %}Unlimited{% endtrans %}
                                            {% if is_granted('ROLE_USER') %}<span class="badge badge-pill badge-success">{{ time.entries }}</span>{% endif %}
                                        {% endif %}
                                    </td>
                                    {% if is_granted('ROLE_USER') %}
                                        <td>
                                            <div class="dropdown dropleft">
                                                <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    A
                                                </button>
                                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                    <a class="dropdown-item" href="{{ path('workshop_registrations', {'workshopId': workshop.id }) }}">{% trans %}View registrations{% endtrans %}</a>
                                                    <a class="dropdown-item" href="{{ path('workshop_update', {'workshopId': workshop.id }) }}">{% trans %}Edit{% endtrans %}</a>
                                                    <a class="dropdown-item" href="{{ path('workshop_update_times', {'workshopId': workshop.id }) }}">{% trans %}Edit Times{% endtrans %}</a>
                                                    <a class="dropdown-item" href="{{ path('download_registrations_workshop', {'workshop': time.id }) }}">{% trans %}Download registrations{% endtrans %} ({% trans %}Single Workshop{% endtrans %})</a>
                                                </div>
                                            </div>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% endif %}
    {% else %}
        <p>{% trans %}Event is empty{% endtrans %}.</p>
    {% endfor %}
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/popper/popper.min.js') }}"></script>
    {{ parent() }}
{% endblock %}

{% block javascript_inline %}
    <script>
        $('.clickable-row .link').hover(function() {
            $(this).parents('.clickable-row').find('.popup').show(200);
        }, function() {
            $(this).parents('.clickable-row').find('.popup').hide(200);
        })
    </script>
{% endblock %}

templates/Default/workshop.html.twig
{% extends 'Default/base.html.twig' %}

{% block title %}{{ workshopTime.workshop.category.event.title }} | {{ workshopTime.workshop.title }} | {{ workshopTime.startTime|date('Y-m-d H:i') }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('style/css/datetimepicker/bootstrap-datetimepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('style/css/select2/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('style/css/select2/select2-bootstrap4.min.css') }}">
{% endblock %}

{% block body %}
    <div class="py-5 text-center">
        <h2>{{ workshopTime.workshop.title }}</h2>
        <h6>{{ workshopTime.startTime|date('Y-m-d H:i') }}</h6>
        <p class="lead">{{ workshopTime.workshop.description|raw }}</p>
    </div>

    <div>
        <iframe class="w-100" frameborder="0" style="border:0" allowfullscreen
                src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBipZdzMFb0iFrTE_5FEFwgmoEXd4--BoM&q={{ workshopTime.workshop.place|url_encode }}">
        </iframe>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8">
            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ label }}" role="alert">
                        {{ message|trans }}
                    </div>
                {% endfor %}
            {% endfor %}
            {% if workshopTime.isAvailable(is_granted('ROLE_USER')) %}
                <h4 class="mb-3">{% trans %}Registration{% endtrans %}</h4>
                <form name="registration" method="post">
                    {% if groupRegistration %}
                        {{ render(controller('App\\Controller\\Event\\FormController::renderForm', { 'config': workshopTime.workshop.groupFormConfig.configParsed })) }}
                    {% else %}
                        {{ render(controller('App\\Controller\\Event\\FormController::renderForm', { 'config': workshopTime.workshop.formConfig.configParsed })) }}
                    {% endif %}
                    <button class="btn btn-primary btn-lg btn-block" type="submit">{% trans %}Register{% endtrans %}</button>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/popper/popper.min.js') }}"></script>
    <script src="{{ asset('js/moment/moment.min.js') }}"></script>
    <script src="{{ asset('js/datetimepicker/bootstrap-datetimepicker.min.js') }}"></script>
    <script src="{{ asset('js/select2/select2.full.min.js') }}"></script>
{% endblock %}

{% block javascript_inline %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();

            $(".datetimepicker").datetimepicker({
                'format': 'YYYY-MM-DD',
                'showClose': true
            });

            $(".formSelect").select2({
                theme: "bootstrap4"
            });
        });
    </script>
{% endblock %}